### ISSUE TITLE
License missing copyright name, year

### ISSUE THREAD

**Issue by xinsight** [ra1028/DiffableDataSources#15]
## Checklist
- [x] Reviewed the README and documents.  
- [x] Searched existing issues for ensure not duplicated.  

## Expected Behavior

The LICENSE file should contain the year of copyright and the name of the copyright holder.

## Current Behavior

The LICENSE file only contains template variables:

`Copyright [yyyy] [name of copyright owner]`

I'm using `Copyright 2019 ra1028` for now, but let me know if you'd prefer something else.

Thanks!

**Comment by ra1028** [comment]
Thanks @xinsight .

Sorry for my late reply.

I'm not familiar with licensing, but most OSSs are the same, so I'd like to keep it.
e.g: https://github.com/apple/swift/blob/master/LICENSE.txt
