### ISSUE TITLE
Add subscript function for SectionIdentifierType

### ISSUE THREAD

**Issue by RalfK92** [ra1028/DiffableDataSources#17]
## Checklist
- [x] Reviewed the README and documents.  
- [x] Searched existing issues for ensure not duplicated.  

## Description
We want to have a getter function for the SectionIdentifierType, to be able to use different cell types depending on the section they are in.

## Motivation and Context
We want to use IBPCollectionViewCompositionalLayout with different layouts per section. IBPCollectionViewCompositionalLayout refers to this datasource library.  In the current implementation we were not able to achieve that because of the missing getter for the SectionIdentifierType.

## Proposed Solution
Adding a subscript function for the SectionIdentifierType.

**Comment by ra1028** [comment]
@RalfK92 
Sorry for my late reply.

Unfortunately, it's not even in the original `UICollectionViewDiffableDataSource`.
I think you can get it from the snapshot.
```swift
dataSource.snapshot().sectionIdentifiers
```
